export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", region: "Asia", currency: "AFN", tier: 3 },
  { code: "AL", name: "Albania", region: "Europe", currency: "ALL", tier: 3 },
  { code: "DZ", name: "Algeria", region: "Africa", currency: "DZD", tier: 3 },
  { code: "AD", name: "Andorra", region: "Europe", currency: "EUR", tier: 2 },
  { code: "AO", name: "Angola", region: "Africa", currency: "AOA", tier: 3 },
  { code: "AG", name: "Antigua and Barbuda", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "AR", name: "Argentina", region: "South America", currency: "ARS", tier: 2 },
  { code: "AM", name: "Armenia", region: "Asia", currency: "AMD", tier: 3 },
  { code: "AU", name: "Australia", region: "Asia Pacific", currency: "AUD", tier: 1 },
  { code: "AT", name: "Austria", region: "Europe", currency: "EUR", tier: 1 },
  { code: "AZ", name: "Azerbaijan", region: "Asia", currency: "AZN", tier: 3 },
  { code: "BS", name: "Bahamas", region: "Caribbean", currency: "BSD", tier: 2 },
  { code: "BH", name: "Bahrain", region: "Middle East", currency: "BHD", tier: 2 },
  { code: "BD", name: "Bangladesh", region: "Asia", currency: "BDT", tier: 3 },
  { code: "BB", name: "Barbados", region: "Caribbean", currency: "BBD", tier: 2 },
  { code: "BY", name: "Belarus", region: "Europe", currency: "BYN", tier: 3 },
  { code: "BE", name: "Belgium", region: "Europe", currency: "EUR", tier: 1 },
  { code: "BZ", name: "Belize", region: "Central America", currency: "BZD", tier: 3 },
  { code: "BJ", name: "Benin", region: "Africa", currency: "XOF", tier: 3 },
  { code: "BT", name: "Bhutan", region: "Asia", currency: "BTN", tier: 3 },
  { code: "BO", name: "Bolivia", region: "South America", currency: "BOB", tier: 3 },
  { code: "BA", name: "Bosnia and Herzegovina", region: "Europe", currency: "BAM", tier: 3 },
  { code: "BW", name: "Botswana", region: "Africa", currency: "BWP", tier: 3 },
  { code: "BR", name: "Brazil", region: "South America", currency: "BRL", tier: 2 },
  { code: "BN", name: "Brunei", region: "Asia", currency: "BND", tier: 2 },
  { code: "BG", name: "Bulgaria", region: "Europe", currency: "BGN", tier: 2 },
  { code: "BF", name: "Burkina Faso", region: "Africa", currency: "XOF", tier: 3 },
  { code: "BI", name: "Burundi", region: "Africa", currency: "BIF", tier: 3 },
  { code: "CV", name: "Cabo Verde", region: "Africa", currency: "CVE", tier: 3 },
  { code: "KH", name: "Cambodia", region: "Asia", currency: "KHR", tier: 3 },
  { code: "CM", name: "Cameroon", region: "Africa", currency: "XAF", tier: 3 },
  { code: "CA", name: "Canada", region: "North America", currency: "CAD", tier: 1 },
  { code: "CF", name: "Central African Republic", region: "Africa", currency: "XAF", tier: 3 },
  { code: "TD", name: "Chad", region: "Africa", currency: "XAF", tier: 3 },
  { code: "CL", name: "Chile", region: "South America", currency: "CLP", tier: 2 },
  { code: "CN", name: "China", region: "Asia", currency: "CNY", tier: 2 },
  { code: "CO", name: "Colombia", region: "South America", currency: "COP", tier: 2 },
  { code: "KM", name: "Comoros", region: "Africa", currency: "KMF", tier: 3 },
  { code: "CG", name: "Congo", region: "Africa", currency: "XAF", tier: 3 },
  { code: "CD", name: "Congo (DRC)", region: "Africa", currency: "CDF", tier: 3 },
  { code: "CR", name: "Costa Rica", region: "Central America", currency: "CRC", tier: 2 },
  { code: "CI", name: "Côte d'Ivoire", region: "Africa", currency: "XOF", tier: 3 },
  { code: "HR", name: "Croatia", region: "Europe", currency: "EUR", tier: 2 },
  { code: "CU", name: "Cuba", region: "Caribbean", currency: "CUP", tier: 3 },
  { code: "CY", name: "Cyprus", region: "Europe", currency: "EUR", tier: 2 },
  { code: "CZ", name: "Czech Republic", region: "Europe", currency: "CZK", tier: 1 },
  { code: "DK", name: "Denmark", region: "Europe", currency: "DKK", tier: 1 },
  { code: "DJ", name: "Djibouti", region: "Africa", currency: "DJF", tier: 3 },
  { code: "DM", name: "Dominica", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "DO", name: "Dominican Republic", region: "Caribbean", currency: "DOP", tier: 2 },
  { code: "EC", name: "Ecuador", region: "South America", currency: "USD", tier: 3 },
  { code: "EG", name: "Egypt", region: "Africa", currency: "EGP", tier: 2 },
  { code: "SV", name: "El Salvador", region: "Central America", currency: "USD", tier: 3 },
  { code: "GQ", name: "Equatorial Guinea", region: "Africa", currency: "XAF", tier: 3 },
  { code: "ER", name: "Eritrea", region: "Africa", currency: "ERN", tier: 3 },
  { code: "EE", name: "Estonia", region: "Europe", currency: "EUR", tier: 1 },
  { code: "SZ", name: "Eswatini", region: "Africa", currency: "SZL", tier: 3 },
  { code: "ET", name: "Ethiopia", region: "Africa", currency: "ETB", tier: 3 },
  { code: "FJ", name: "Fiji", region: "Asia Pacific", currency: "FJD", tier: 3 },
  { code: "FI", name: "Finland", region: "Europe", currency: "EUR", tier: 1 },
  { code: "FR", name: "France", region: "Europe", currency: "EUR", tier: 1 },
  { code: "GA", name: "Gabon", region: "Africa", currency: "XAF", tier: 3 },
  { code: "GM", name: "Gambia", region: "Africa", currency: "GMD", tier: 3 },
  { code: "GE", name: "Georgia", region: "Asia", currency: "GEL", tier: 3 },
  { code: "DE", name: "Germany", region: "Europe", currency: "EUR", tier: 1 },
  { code: "GH", name: "Ghana", region: "Africa", currency: "GHS", tier: 2 },
  { code: "GR", name: "Greece", region: "Europe", currency: "EUR", tier: 2 },
  { code: "GD", name: "Grenada", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "GT", name: "Guatemala", region: "Central America", currency: "GTQ", tier: 3 },
  { code: "GN", name: "Guinea", region: "Africa", currency: "GNF", tier: 3 },
  { code: "GW", name: "Guinea-Bissau", region: "Africa", currency: "XOF", tier: 3 },
  { code: "GY", name: "Guyana", region: "South America", currency: "GYD", tier: 3 },
  { code: "HT", name: "Haiti", region: "Caribbean", currency: "HTG", tier: 3 },
  { code: "HN", name: "Honduras", region: "Central America", currency: "HNL", tier: 3 },
  { code: "HU", name: "Hungary", region: "Europe", currency: "HUF", tier: 2 },
  { code: "IS", name: "Iceland", region: "Europe", currency: "ISK", tier: 1 },
  { code: "IN", name: "India", region: "Asia", currency: "INR", tier: 2 },
  { code: "ID", name: "Indonesia", region: "Asia", currency: "IDR", tier: 2 },
  { code: "IR", name: "Iran", region: "Middle East", currency: "IRR", tier: 3 },
  { code: "IQ", name: "Iraq", region: "Middle East", currency: "IQD", tier: 3 },
  { code: "IE", name: "Ireland", region: "Europe", currency: "EUR", tier: 1 },
  { code: "IL", name: "Israel", region: "Middle East", currency: "ILS", tier: 2 },
  { code: "IT", name: "Italy", region: "Europe", currency: "EUR", tier: 1 },
  { code: "JM", name: "Jamaica", region: "Caribbean", currency: "JMD", tier: 3 },
  { code: "JP", name: "Japan", region: "Asia", currency: "JPY", tier: 1 },
  { code: "JO", name: "Jordan", region: "Middle East", currency: "JOD", tier: 2 },
  { code: "KZ", name: "Kazakhstan", region: "Asia", currency: "KZT", tier: 2 },
  { code: "KE", name: "Kenya", region: "Africa", currency: "KES", tier: 2 },
  { code: "KW", name: "Kuwait", region: "Middle East", currency: "KWD", tier: 2 },
  { code: "KG", name: "Kyrgyzstan", region: "Asia", currency: "KGS", tier: 3 },
  { code: "LA", name: "Laos", region: "Asia", currency: "LAK", tier: 3 },
  { code: "LV", name: "Latvia", region: "Europe", currency: "EUR", tier: 1 },
  { code: "LB", name: "Lebanon", region: "Middle East", currency: "LBP", tier: 3 },
  { code: "LS", name: "Lesotho", region: "Africa", currency: "LSL", tier: 3 },
  { code: "LR", name: "Liberia", region: "Africa", currency: "LRD", tier: 3 },
  { code: "LY", name: "Libya", region: "Africa", currency: "LYD", tier: 3 },
  { code: "LI", name: "Liechtenstein", region: "Europe", currency: "CHF", tier: 1 },
  { code: "LT", name: "Lithuania", region: "Europe", currency: "EUR", tier: 1 },
  { code: "LU", name: "Luxembourg", region: "Europe", currency: "EUR", tier: 1 },
  { code: "MG", name: "Madagascar", region: "Africa", currency: "MGA", tier: 3 },
  { code: "MW", name: "Malawi", region: "Africa", currency: "MWK", tier: 3 },
  { code: "MY", name: "Malaysia", region: "Asia", currency: "MYR", tier: 2 },
  { code: "MV", name: "Maldives", region: "Asia", currency: "MVR", tier: 2 },
  { code: "ML", name: "Mali", region: "Africa", currency: "XOF", tier: 3 },
  { code: "MT", name: "Malta", region: "Europe", currency: "EUR", tier: 2 },
  { code: "MR", name: "Mauritania", region: "Africa", currency: "MRU", tier: 3 },
  { code: "MU", name: "Mauritius", region: "Africa", currency: "MUR", tier: 2 },
  { code: "MX", name: "Mexico", region: "North America", currency: "MXN", tier: 2 },
  { code: "MD", name: "Moldova", region: "Europe", currency: "MDL", tier: 3 },
  { code: "MC", name: "Monaco", region: "Europe", currency: "EUR", tier: 1 },
  { code: "MN", name: "Mongolia", region: "Asia", currency: "MNT", tier: 3 },
  { code: "ME", name: "Montenegro", region: "Europe", currency: "EUR", tier: 3 },
  { code: "MA", name: "Morocco", region: "Africa", currency: "MAD", tier: 2 },
  { code: "MZ", name: "Mozambique", region: "Africa", currency: "MZN", tier: 3 },
  { code: "MM", name: "Myanmar", region: "Asia", currency: "MMK", tier: 3 },
  { code: "NA", name: "Namibia", region: "Africa", currency: "NAD", tier: 3 },
  { code: "NP", name: "Nepal", region: "Asia", currency: "NPR", tier: 3 },
  { code: "NL", name: "Netherlands", region: "Europe", currency: "EUR", tier: 1 },
  { code: "NZ", name: "New Zealand", region: "Asia Pacific", currency: "NZD", tier: 1 },
  { code: "NI", name: "Nicaragua", region: "Central America", currency: "NIO", tier: 3 },
  { code: "NE", name: "Niger", region: "Africa", currency: "XOF", tier: 3 },
  { code: "NG", name: "Nigeria", region: "Africa", currency: "NGN", tier: 2 },
  { code: "MK", name: "North Macedonia", region: "Europe", currency: "MKD", tier: 3 },
  { code: "NO", name: "Norway", region: "Europe", currency: "NOK", tier: 1 },
  { code: "OM", name: "Oman", region: "Middle East", currency: "OMR", tier: 2 },
  { code: "PK", name: "Pakistan", region: "Asia", currency: "PKR", tier: 3 },
  { code: "PA", name: "Panama", region: "Central America", currency: "PAB", tier: 2 },
  { code: "PG", name: "Papua New Guinea", region: "Asia Pacific", currency: "PGK", tier: 3 },
  { code: "PY", name: "Paraguay", region: "South America", currency: "PYG", tier: 3 },
  { code: "PE", name: "Peru", region: "South America", currency: "PEN", tier: 2 },
  { code: "PH", name: "Philippines", region: "Asia", currency: "PHP", tier: 2 },
  { code: "PL", name: "Poland", region: "Europe", currency: "PLN", tier: 1 },
  { code: "PT", name: "Portugal", region: "Europe", currency: "EUR", tier: 1 },
  { code: "QA", name: "Qatar", region: "Middle East", currency: "QAR", tier: 2 },
  { code: "RO", name: "Romania", region: "Europe", currency: "RON", tier: 2 },
  { code: "RU", name: "Russia", region: "Europe", currency: "RUB", tier: 2 },
  { code: "RW", name: "Rwanda", region: "Africa", currency: "RWF", tier: 3 },
  { code: "KN", name: "Saint Kitts and Nevis", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "LC", name: "Saint Lucia", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "VC", name: "Saint Vincent and the Grenadines", region: "Caribbean", currency: "XCD", tier: 3 },
  { code: "WS", name: "Samoa", region: "Asia Pacific", currency: "WST", tier: 3 },
  { code: "SM", name: "San Marino", region: "Europe", currency: "EUR", tier: 2 },
  { code: "ST", name: "São Tomé and Príncipe", region: "Africa", currency: "STN", tier: 3 },
  { code: "SA", name: "Saudi Arabia", region: "Middle East", currency: "SAR", tier: 2 },
  { code: "SN", name: "Senegal", region: "Africa", currency: "XOF", tier: 3 },
  { code: "RS", name: "Serbia", region: "Europe", currency: "RSD", tier: 3 },
  { code: "SC", name: "Seychelles", region: "Africa", currency: "SCR", tier: 2 },
  { code: "SL", name: "Sierra Leone", region: "Africa", currency: "SLL", tier: 3 },
  { code: "SG", name: "Singapore", region: "Asia", currency: "SGD", tier: 1 },
  { code: "SK", name: "Slovakia", region: "Europe", currency: "EUR", tier: 1 },
  { code: "SI", name: "Slovenia", region: "Europe", currency: "EUR", tier: 1 },
  { code: "SB", name: "Solomon Islands", region: "Asia Pacific", currency: "SBD", tier: 3 },
  { code: "SO", name: "Somalia", region: "Africa", currency: "SOS", tier: 3 },
  { code: "ZA", name: "South Africa", region: "Africa", currency: "ZAR", tier: 2 },
  { code: "SS", name: "South Sudan", region: "Africa", currency: "SSP", tier: 3 },
  { code: "ES", name: "Spain", region: "Europe", currency: "EUR", tier: 1 },
  { code: "LK", name: "Sri Lanka", region: "Asia", currency: "LKR", tier: 3 },
  { code: "SD", name: "Sudan", region: "Africa", currency: "SDG", tier: 3 },
  { code: "SR", name: "Suriname", region: "South America", currency: "SRD", tier: 3 },
  { code: "SE", name: "Sweden", region: "Europe", currency: "SEK", tier: 1 },
  { code: "CH", name: "Switzerland", region: "Europe", currency: "CHF", tier: 1 },
  { code: "SY", name: "Syria", region: "Middle East", currency: "SYP", tier: 3 },
  { code: "TW", name: "Taiwan", region: "Asia", currency: "TWD", tier: 1 },
  { code: "TJ", name: "Tajikistan", region: "Asia", currency: "TJS", tier: 3 },
  { code: "TZ", name: "Tanzania", region: "Africa", currency: "TZS", tier: 3 },
  { code: "TH", name: "Thailand", region: "Asia", currency: "THB", tier: 2 },
  { code: "TL", name: "Timor-Leste", region: "Asia", currency: "USD", tier: 3 },
  { code: "TG", name: "Togo", region: "Africa", currency: "XOF", tier: 3 },
  { code: "TO", name: "Tonga", region: "Asia Pacific", currency: "TOP", tier: 3 },
  { code: "TT", name: "Trinidad and Tobago", region: "Caribbean", currency: "TTD", tier: 2 },
  { code: "TN", name: "Tunisia", region: "Africa", currency: "TND", tier: 3 },
  { code: "TR", name: "Turkey", region: "Europe", currency: "TRY", tier: 2 },
  { code: "TM", name: "Turkmenistan", region: "Asia", currency: "TMT", tier: 3 },
  { code: "TV", name: "Tuvalu", region: "Asia Pacific", currency: "AUD", tier: 3 },
  { code: "UG", name: "Uganda", region: "Africa", currency: "UGX", tier: 3 },
  { code: "UA", name: "Ukraine", region: "Europe", currency: "UAH", tier: 3 },
  { code: "AE", name: "United Arab Emirates", region: "Middle East", currency: "AED", tier: 2 },
  { code: "GB", name: "United Kingdom", region: "Europe", currency: "GBP", tier: 1 },
  { code: "US", name: "United States", region: "North America", currency: "USD", tier: 1 },
  { code: "UY", name: "Uruguay", region: "South America", currency: "UYU", tier: 2 },
  { code: "UZ", name: "Uzbekistan", region: "Asia", currency: "UZS", tier: 3 },
  { code: "VU", name: "Vanuatu", region: "Asia Pacific", currency: "VUV", tier: 3 },
  { code: "VE", name: "Venezuela", region: "South America", currency: "VES", tier: 3 },
  { code: "VN", name: "Vietnam", region: "Asia", currency: "VND", tier: 2 },
  { code: "YE", name: "Yemen", region: "Middle East", currency: "YER", tier: 3 },
  { code: "ZM", name: "Zambia", region: "Africa", currency: "ZMW", tier: 3 },
  { code: "ZW", name: "Zimbabwe", region: "Africa", currency: "ZWL", tier: 3 },
];

export const QUICK_SELECT_COUNTRIES = ["GB", "NG", "US", "CA", "GH", "KE", "ZA", "AE", "DE", "FR"];

export const COUNTRY_EMAIL_TONES: Record<string, { tone: string; description: string }> = {
  GB: { tone: "formal, concise, direct", description: "Formal and professional" },
  US: { tone: "confident, value-led, ROI-focused", description: "Confident and results-oriented" },
  CA: { tone: "formal, concise, direct", description: "Professional and straightforward" },
  AU: { tone: "formal, concise, direct", description: "Direct and professional" },
  NZ: { tone: "formal, concise, direct", description: "Professional and friendly" },
  NG: { tone: "warm, relationship-first, local context-aware", description: "Warm and relationship-focused" },
  GH: { tone: "warm, relationship-first, local context-aware", description: "Warm and relationship-first" },
  KE: { tone: "warm, relationship-first, local context-aware", description: "Professional and warm" },
  ZA: { tone: "warm, relationship-first, local context-aware", description: "Warm and relationship-aware" },
  AE: { tone: "formal, prestige and exclusivity emphasized", description: "Premium and exclusive" },
  SA: { tone: "formal, prestige and exclusivity emphasized", description: "Formal and prestigious" },
  DE: { tone: "precise, structured, fact-based", description: "Precise and structured" },
  NL: { tone: "precise, structured, fact-based", description: "Direct and structured" },
  FR: { tone: "relationship-aware, quality-led", description: "Relationship-focused, quality-led" },
  IT: { tone: "relationship-aware, quality-led", description: "Relationship and quality-focused" },
  ES: { tone: "relationship-aware, quality-led", description: "Warm and relationship-aware" },
  IN: { tone: "professional, detail-oriented, scale-focused", description: "Professional and detail-oriented" },
  SG: { tone: "professional, detail-oriented, scale-focused", description: "Professional and precise" },
  JP: { tone: "professional, respectful, formal", description: "Respectful and formal" },
  CN: { tone: "professional, respect-focused, hierarchical", description: "Professional and hierarchical" },
  BR: { tone: "warm, relationship-first, personal", description: "Warm and personal" },
  MX: { tone: "warm, respectful, relationship-first", description: "Warm and respectful" },
  AR: { tone: "warm, relationship-first, direct", description: "Warm and direct" },
  CH: { tone: "precise, structured, professional", description: "Precise and professional" },
  AT: { tone: "precise, structured, formal", description: "Formal and structured" },
  BE: { tone: "professional, multilingual respect", description: "Professional and inclusive" },
  IE: { tone: "friendly, professional, conversational", description: "Friendly and professional" },
};

export function getCurrencyByCountry(countryCode: string): string {
  const country = COUNTRIES.find(c => c.code === countryCode);
  return country?.currency || "GBP";
}

export function getCountryTier(countryCode: string): 1 | 2 {
  const country = COUNTRIES.find(c => c.code === countryCode);
  return (country?.tier as 1 | 2) || 2;
}

export function getEmailToneByCountry(countryCode: string): string {
  return COUNTRY_EMAIL_TONES[countryCode]?.tone || COUNTRY_EMAIL_TONES["GB"].tone;
}

export function getCountryName(countryCode: string): string {
  return COUNTRIES.find(c => c.code === countryCode)?.name || countryCode;
}